# microbiome_repo-pipeline — monthly cycle targets (docs/RUNBOOK.md has the narrative, budgets and stop rules).
# Every target is deterministic EXCEPT triage and extract, which call host.llm and therefore must run inside a
# Claude Science session (root frame with delegation on). PYTHONPATH=src makes `import catalog` work.
SHELL      := bash
PY         ?= python
export PYTHONPATH := $(CURDIR)/src:$(PYTHONPATH)
export CATALOG_CONFIG_DIR := $(CURDIR)/config

VERSION    := $(shell cat config/version.txt)
DATA       ?= data/inputs
# PKG_ZIP: the CURRENT release package zip (explicit, never a glob — R1-03); PKG_SRC: where `unpack` flattens it
# default = the previous package of the release being built (config/releases.yaml previous_package_version); override explicitly when needed
PREV_PKG   := $(shell $(PY) -c "import yaml;c=yaml.safe_load(open('config/releases.yaml'));print(next((r.get('previous_package_version','') for r in c['releases'] if r['package_version']=='$(VERSION)'),''))")
PKG_ZIP    ?= $(DATA)/data_package_v$(PREV_PKG).zip
PKG_SRC    ?= $(DATA)/data_package
BUILD      ?= build
PKG_OUT    := $(BUILD)/package
PKG_ZIP_OUT:= $(BUILD)/data_package_v$(VERSION).zip
# Release model (config/releases.yaml, docs/RELEASES.md): RELEASE_ID for VERSION, PREV_VERSION from the unpacked source package
RELEASE_ID := $(shell $(PY) -c "import yaml;c=yaml.safe_load(open('config/releases.yaml'));print(next((r['release_id'] for r in c['releases'] if r['package_version']=='$(VERSION)'),''))")
PREV_VERSION = $(shell $(PY) -c "import json;print(json.load(open('$(PKG_SRC)/VERSION.json'))['package_version'])")
RELEASE_NOTES := $(PKG_OUT)/RELEASE_NOTES_$(RELEASE_ID).md
APPLIED    := $(BUILD)/applied_$(VERSION)
SITE_OUT   := $(BUILD)/site
# staging repo for large release assets — outside the host grant (a .git cannot be created under ~/catalog); no trailing comment here (Make keeps blanks)
ASSETS_WT  := /tmp/release_assets_$(VERSION)
SITE_CLONE ?= $(HOME)/catalog/infant-gut-catalog
DATA_CLONE ?= $(HOME)/catalog/infant-gut-catalog-data
# site.yaml is parsed with PyYAML (R1-19): base_url must differ from placeholder_base_url
BASE_URL   := $(shell $(PY) -c "import yaml;print(yaml.safe_load(open('config/site.yaml'))['site']['base_url'])")
PLACEHOLDER_URL := $(shell $(PY) -c "import yaml;print(yaml.safe_load(open('config/site.yaml'))['site'].get('placeholder_base_url',''))")
BUILD_DATE ?= $(shell date +%F)
# VERDICTS: optional parquet of validated triage verdicts for NEW studies judged this cycle (RUNBOOK §2); applied before bitemporal
VERDICTS   ?=
CYCLE      ?= $(shell date +%Y-%m)
REPORTS    ?= $(DATA)/reports
# Sandpiper snapshot (R3-4 / R1-14): override for a new Zenodo version
ZENODO_RECORD     ?= 20419175
SANDPIPER_VERSION ?= 2.0.0
SP_DIR     := $(BUILD)/sandpiper_$(ZENODO_RECORD)
EXTERNAL   ?= $(HOME)/catalog/external
export SANDPIPER_ZENODO_RECORD := $(ZENODO_RECORD)
export SANDPIPER_VERSION

.PHONY: gut-build gut-newfields-r1 gut-newfields-r1-v2 registry-fixture registry-classify-det registry-build registry-biosamples help gapfill apply-gapfill ingest-contributions apply-verdicts bootstrap bootstrap-kernel lock check-credential unpack inputs-json sync-skills test resweep triage extract findings rewide package package-assemble bitemporal worklist package-docs release-notes release check-reports plot-coverage site verify publish-branch install-workflows ingest-issues sandpiper-refresh sandpiper-delta authors clean

help:            ## list targets
	@grep -E '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) | awk 'BEGIN{FS=":.*?## "}{printf "  %-16s %s\n", $$1, $$2}'

bootstrap:       ## create env, pull inputs from ~/catalog/data, verify hashes, run tests (exit 4 = required input missing)
	$(PY) bootstrap.py

bootstrap-kernel: ## print the in-kernel form (artifact store reachable through the kernel `host` global) — R1-02
	@echo "run in a Claude Science python cell (env infantcat):"
	@echo "  __file__ = '$(CURDIR)/bootstrap.py'; exec(open(__file__).read()); rc = main(['--no-env', '--only-required']); print('bootstrap rc', rc)"

lock:            ## regenerate requirements.lock + environment.lock.yml from the active env (no file:// URLs) — R1-04
	{ echo "# pip list --format=freeze of the infantcat env, $$(date +%F) (python $$($(PY) -c 'import platform;print(platform.python_version())')). No file:// URLs (R1-04)."; \
	  echo "# appnope is macOS-only; environment marker added so Linux CI can install this file."; \
	  $(PY) -m pip list --format=freeze | grep -v '^microbiome_repo-pipeline' | sed 's/^appnope==\(.*\)$$/appnope==\1; sys_platform == "darwin"/'; } > requirements.lock
	$(PY) - <<-'EOF'
	import platform
	lines=[l.strip() for l in open('requirements.lock') if l.strip() and not l.startswith('#')]
	out=["# environment.lock.yml — exact pins for the infantcat env (generated by `make lock`; conda installs python, pip installs the pins).",
	     "name: infantcat","channels: [conda-forge]","dependencies:",f"  - python={platform.python_version()}","  - pip","  - pip:"]+[f"      - {l}" for l in lines]
	open('environment.lock.yml','w').write("\n".join(out)+"\n")
	EOF

unpack:          ## unzip PKG_ZIP into $(PKG_SRC), flattening a single top-level dir (package_v1.2.1/…) — R1-03
	@test -f "$(PKG_ZIP)" || { echo "PKG_ZIP=$(PKG_ZIP) not found (bootstrap materialises it into $(DATA)/)"; exit 1; }
	rm -rf $(PKG_SRC) && mkdir -p $(PKG_SRC) && unzip -q "$(PKG_ZIP)" -d $(PKG_SRC)
	@if [ ! -f $(PKG_SRC)/sample_metadata_wide.parquet ]; then \
	  top=$$(ls -A $(PKG_SRC)); n=$$(echo "$$top" | wc -l | tr -d ' '); \
	  if [ "$$n" = "1" ] && [ -d "$(PKG_SRC)/$$top" ]; then mv "$(PKG_SRC)/$$top"/* $(PKG_SRC)/ && rmdir "$(PKG_SRC)/$$top"; echo "flattened $$top/"; \
	  else echo "unexpected zip layout in $(PKG_ZIP)"; exit 1; fi; fi
	@test -f $(PKG_SRC)/sample_metadata_wide.parquet && echo "unpacked → $(PKG_SRC)"

inputs-json:     ## recompute sha256_repo for every code entry in config/inputs.json (after an intentional edit)
	$(PY) scripts/inputs_json.py

sync-skills:     ## (Claude session only) re-vendor skills/ from host.skills.read — see RUNBOOK §0
	@echo "run in the repl tool: for f in ('SKILL.md','kernel.py'): open('skills/infant-curation-rules/'+f,'w').write(host.skills.read('infant-curation-rules', path=f)['content'])"

test:            ## unit tests (hash, validator sync, model resolution, package determinism — all must pass)
	$(PY) -m pytest tests -q

# SINCE: first_public >= SINCE (overlap one week)
SINCE ?= $(shell date -v-35d +%F 2>/dev/null || date -d '35 days ago' +%F)
# CACHE_DIR: holds harvest_cache/ (untarred)
CACHE_DIR ?= $(HOME)/catalog/cache

resweep:         ## stage 1 — frame-free monthly re-sweep of ENA (deterministic, network; needs harvest cache)
	mkdir -p $(BUILD)/resweep_$(CYCLE) && cd $(BUILD)/resweep_$(CYCLE) && \
	cp $(CURDIR)/$(DATA)/catalog_studies.parquet . && \
	{ [ -e harvest_cache ] || ln -s $(CACHE_DIR)/harvest_cache harvest_cache; } && \
	$(PY) $(CURDIR)/src/catalog/enumeration/resweep_universe.py --since $(SINCE) --catalog catalog_studies.parquet --out . 2>&1 | tee resweep.log

registry-enumerate: ## scale-up S1a — registry UNIVERSE: every ENA study that could hold human shotgun metagenomes (frame-free S1 + misfiled GENOMIC S2 + OTHER/TC/WGA adjudication S3; deterministic, network, ≈ 1 h; REGISTRY_SLICES="S1 S2 S3", REGISTRY_SINCE= optional)
	mkdir -p $(BUILD)/registry && \
	CATALOG_CACHE_DIR=$(CACHE_DIR) $(PY) $(CURDIR)/src/catalog/registry/enumerate_registry.py --out $(BUILD)/registry \
	  --slices $(or $(REGISTRY_SLICES),S1 S2 S3) $(if $(REGISTRY_SINCE),--since $(REGISTRY_SINCE),) \
	  --infant-universe $(PKG_SRC)/universe_studies_all.parquet 2>&1 | tee $(BUILD)/registry/run.log

sandpiper-refresh: ## stage 1c — NEW Sandpiper Zenodo version: download bulk, prepare inputs, filter, build tables, report (≈ 70 min, 1 GB RAM/24 GB DuckDB)
	mkdir -p $(SP_DIR)/sp $(SP_DIR)/handoff && cd $(SP_DIR) && \
	{ [ -f sp/sandpiper$(SANDPIPER_VERSION).gtdb.csv.gz ] || [ ! -f $(EXTERNAL)/sandpiper/$(SANDPIPER_VERSION)/sandpiper$(SANDPIPER_VERSION).gtdb.csv.gz ] || ln -s $(EXTERNAL)/sandpiper/$(SANDPIPER_VERSION)/sandpiper$(SANDPIPER_VERSION).gtdb.csv.gz sp/; } && \
	$(PY) $(CURDIR)/src/catalog/sandpiper/download_bulk.py && \
	$(MAKE) -C $(CURDIR) sandpiper-delta ZENODO_RECORD=$(ZENODO_RECORD) SANDPIPER_VERSION=$(SANDPIPER_VERSION)
	@echo "then: copy sp/sandpiper_*.{parquet,csv} + SANDPIPER_REPORT.md into the package (make package-merge) and store the bulk file under $(EXTERNAL)/sandpiper/$(SANDPIPER_VERSION)/ + as ONE snapshot artifact (docs/DATA_LAYOUT.md)"

sandpiper-delta: ## stage 1b (Curator) — re-derive the Sandpiper tables for the current catalog from the CURRENT snapshot (no download; ≈ 40 min)
	@test -f $(PKG_SRC)/sample_metadata_wide.parquet || { echo "run make unpack first"; exit 1; }
	mkdir -p $(SP_DIR)/sp $(SP_DIR)/handoff && cd $(SP_DIR) && \
	{ [ -f sp/sandpiper$(SANDPIPER_VERSION).gtdb.csv.gz ] || { [ -f $(EXTERNAL)/sandpiper/$(SANDPIPER_VERSION)/sandpiper$(SANDPIPER_VERSION).gtdb.csv.gz ] && ln -s $(EXTERNAL)/sandpiper/$(SANDPIPER_VERSION)/sandpiper$(SANDPIPER_VERSION).gtdb.csv.gz sp/; } || { echo "bulk snapshot missing: $(EXTERNAL)/sandpiper/$(SANDPIPER_VERSION)/ (or make sandpiper-refresh; snapshot artifact id in config/inputs.json)"; exit 1; }; } && \
	$(PY) -m catalog.sandpiper.prepare_inputs --match $(CURDIR)/$(DATA)/sandpiper/catalog_runs_sandpiper_match.parquet \
	  --per-acc $(CURDIR)/$(DATA)/sandpiper/sandpiper$(SANDPIPER_VERSION).per_acc_summary.csv.gz --package $(CURDIR)/$(PKG_SRC) --out sp && \
	$(PY) $(CURDIR)/src/catalog/sandpiper/filter_bulk.py && \
	$(PY) $(CURDIR)/src/catalog/sandpiper/build_sandpiper_tables.py && \
	{ [ -f handoff/report_numbers.json ] && $(PY) $(CURDIR)/src/catalog/sandpiper/render_report.py || echo "render_report.py skipped: handoff/report_numbers.json not present (see src/catalog/sandpiper/README.md)"; }

authors:         ## author index rebuild — NCBI BioProject XML for every catalog study (≈ 25 min, ≈ 60 esearch + 60 efetch requests per 6k studies; cache-through)
	mkdir -p $(BUILD)/authors_$(CYCLE) && cd $(BUILD)/authors_$(CYCLE) && \
	CATALOG_CACHE_DIR=$(CACHE_DIR) $(PY) $(CURDIR)/src/catalog/authors/harvest_bioproject_authors.py $(CURDIR)/$(DATA)/catalog_studies.parquet && ls -la bioproject_records.parquet

triage:          ## stage 2 — LLM triage of new candidates (Claude session; leaf workers exec run_sonnet_confirm.py)
	@echo "LLM stage: follow docs/RUNBOOK.md §2 (dispatch leaf workers from the root session; stop rule >300 candidates)"; exit 2

extract:         ## stage 3 — per-sample extraction R1–R4 for NEW included studies (Claude session)
	@echo "LLM stage: follow docs/RUNBOOK.md §3"; exit 2

# ---- stage 3b: new samples in an INCLUDED study (RUNBOOK §3 'new samples in an included study'; deterministic, network) ----
# GAPFILL_STUDY: study accession; GAPFILL_NEW_RUNS: ENA read_run rows of the new runs (resweep output); GAPFILL_SANDPIPER=1 calls the
# per-run Sandpiper API (<= 0.5 req/s, cache-through); GAPFILL_OUT defaults to build/gapfill_$(RELEASE_ID)
GAPFILL_STUDY    ?=
GAPFILL_NEW_RUNS ?=
GAPFILL_OUT      ?= $(BUILD)/gapfill_$(RELEASE_ID)
GAPFILL_SANDPIPER ?= 1
gapfill:         ## stage 3b — build package-shaped rows for new runs of an included study (GAPFILL_STUDY=PRJ… GAPFILL_NEW_RUNS=…parquet)
	@test -n "$(GAPFILL_STUDY)" -a -n "$(GAPFILL_NEW_RUNS)" || { echo "usage: make gapfill GAPFILL_STUDY=PRJNA… GAPFILL_NEW_RUNS=path/new_runs.parquet"; exit 2; }
	@test -f $(PKG_SRC)/sample_metadata_wide.parquet || { echo "run make unpack first"; exit 1; }
	CATALOG_CACHE_DIR=$(CACHE_DIR) $(PY) -m catalog.extraction.gapfill_samples --study $(GAPFILL_STUDY) --new-runs $(GAPFILL_NEW_RUNS) --package $(PKG_SRC) \
	  --out $(GAPFILL_OUT) --release-id $(RELEASE_ID) --package-version $(VERSION) --field-map config/attribute_field_map.csv --harvest-existing \
	  $(if $(filter 1,$(GAPFILL_SANDPIPER)),--sandpiper,)

apply-gapfill:   ## stage 3b — append $(GAPFILL_OUT) to $(PKG_OUT) (no existing row changes; asserted) — runs inside `make release` when GAPFILL_OUT holds outputs
	@test -f $(GAPFILL_OUT)/samples_new_wide.parquet || { echo "run make gapfill first ($(GAPFILL_OUT))"; exit 1; }
	$(PY) -m catalog.release.apply_gapfill --package $(PKG_OUT) --gapfill $(GAPFILL_OUT)   # on the ASSEMBLED dir: PKG_SRC stays the pristine previous package for bitemporal/release-notes

findings:        ## stage 4 — apply audit/findings/*.csv with validators; rebuilds wide + study lists; output in $(APPLIED) (versioned, R1-16)
	@test -f "$(PKG_SRC)/sample_metadata_wide.parquet" || { echo "run make unpack first"; exit 1; }
	rm -rf $(APPLIED) && $(PY) -m catalog.apply_findings --package $(PKG_SRC) --findings audit/findings --out $(APPLIED)

ingest-issues:   ## pull GitHub Issues labelled `finding` into audit/findings/<date>_issues.csv (needs GITHUB_TOKEN or GH_TOKEN; R1-09/F2)
	$(PY) -m catalog.ingest_issues --repo $$($(PY) -c "import yaml;c=yaml.safe_load(open('config/site.yaml'));print(c['github']['org']+'/'+c['github']['issues']['repo'])") --out audit/findings

ingest-contributions: ## R2026.2 — Issues labelled `contribution` → audit/contributions/<issue>/ (attachments, manifest, joinability verdict); GITHUB_TOKEN optional for reads, required with COMMENT=1
	$(PY) -m catalog.contribute.ingest_contributions --repo $$($(PY) -c "import yaml;c=yaml.safe_load(open('config/contribute.yaml'));print(c['issue_form']['repo'])") \
	  --package $(PKG_SRC) --out audit/contributions $(if $(SINCE_ISO),--since $(SINCE_ISO)) $(if $(COMMENT),--comment)

package-assemble: ## stage 5a — findings → package dir = PKG_SRC + applied tables (shared by `package` and `release`)
	@test -n "$(PKG_SRC)" && test -f "$(PKG_SRC)/sample_metadata_wide.parquet" || { echo "PKG_SRC=$(PKG_SRC) is not an unpacked package (run make unpack)"; exit 1; }
	@test -n "$(PKG_OUT)" && test "$(PKG_OUT)" != "/" || exit 1
	$(MAKE) findings
	mkdir -p $(PKG_OUT) && rsync -a --delete $(PKG_SRC)/ $(PKG_OUT)/
	@if [ -f $(APPLIED)/APPLIED ]; then cp $(APPLIED)/*.parquet $(APPLIED)/*.csv $(PKG_OUT)/ 2>/dev/null; cp $(APPLIED)/APPLY_FINDINGS_DIFF.md $(PKG_OUT)/; echo "applied tables copied from $(APPLIED)"; else echo "no applied findings (nothing copied)"; fi

package:         ## stage 5 — package dir (+ applied tables) → VERSION.json → deterministic zip + sidecar (R1-11); `findings` always re-runs first
	$(MAKE) package-assemble
	$(PY) -m catalog.make_version --package $(PKG_OUT) --build-date $(BUILD_DATE) --zip $(PKG_ZIP_OUT)
	$(PY) -m catalog.make_version --package $(PKG_OUT) --check --zip $(PKG_ZIP_OUT)
	@ls -la $(PKG_ZIP_OUT) && cat $(PKG_ZIP_OUT).sha256

bitemporal:      ## stage 5b — release columns on every fact table + sample_determinations_all.parquet + releases.csv (config/releases.yaml; docs/RELEASES.md)
	@test -n "$(RELEASE_ID)" || { echo "config/releases.yaml has no release for package $(VERSION) — add it under releases:"; exit 1; }
	@test -f "$(PKG_OUT)/sample_determinations.parquet" || { echo "run make package-assemble first"; exit 1; }
	$(PY) -m catalog.release.bitemporal --package $(PKG_OUT) --out $(PKG_OUT) --release-id $(RELEASE_ID) --package-version $(VERSION) \
	  --previous-package-version $(PREV_VERSION) --previous-package $(PKG_SRC) --release-date $(BUILD_DATE)

worklist:        ## stage 4b — contribute_worklist.csv + contribute_worklist_fields.csv from the package + $(DATA)/contribute inputs (config/contribute.yaml; docs/CONTRIBUTE.md)
	@test -f "$(PKG_OUT)/sample_determinations.parquet" || { echo "run make package-assemble first"; exit 1; }
	@test -f "$(DATA)/contribute/recoverability.parquet" || { echo "artifact inputs missing under $(DATA)/contribute (bootstrap.py materialises config/inputs.json group contribute)"; exit 1; }
	$(PY) -m catalog.contribute.build_worklist --package $(PKG_OUT) --inputs $(DATA)/contribute --out $(PKG_OUT) \
	  --release-id $(RELEASE_ID) --package-version $(VERSION) --report $(BUILD)/WORKLIST_REPORT.md

package-docs:    ## stage 5c — build_counts.json from the tables; README heading/Files table, DATA_DICTIONARY release columns, CHANGELOG entry (docs/package_changelog/$(VERSION).md)
	$(PY) -m catalog.release.package_docs --package $(PKG_OUT) --package-version $(VERSION) --release-id $(RELEASE_ID) --build-date $(BUILD_DATE) \
	  --changelog-entry docs/package_changelog/$(VERSION).md --readme-intro docs/package_readme_intro.md

release-notes:   ## stage 5d — RELEASE_NOTES_<release_id>.md from PKG_SRC (previous) vs PKG_OUT (new); deterministic
	$(PY) -m catalog.release.release_notes --prev $(PKG_SRC) --new $(PKG_OUT) --out $(RELEASE_NOTES)

release:         ## stage 5 (R2026.n) — unpack → findings → assemble → bitemporal → worklist → package-docs → VERSION.json → release notes → VERSION.json+zip → check
	@test -n "$(RELEASE_ID)" || { echo "config/releases.yaml has no release for package $(VERSION)"; exit 1; }
	@if [ -z "$(SKIP_UNPACK)" ]; then $(MAKE) unpack; else echo "SKIP_UNPACK set: using the already unpacked $(PKG_SRC)"; fi
	$(MAKE) package-assemble
	@if [ -n "$(VERDICTS)" ]; then $(MAKE) apply-verdicts; else echo "no VERDICTS given (no new studies this cycle)"; fi
	@if [ -f "$(GAPFILL_OUT)/samples_new_wide.parquet" ]; then $(MAKE) apply-gapfill; else echo "no gap-fill outputs in $(GAPFILL_OUT)"; fi
	$(MAKE) bitemporal
	$(MAKE) worklist
	@if [ -f "$(REGISTRY_UNIVERSE)" ]; then $(MAKE) registry-build REGISTRY_OUT=$(PKG_OUT) && rm -f $(PKG_OUT)/registry_studies_fixture.parquet; else echo "no registry universe at $(REGISTRY_UNIVERSE) (registry tables not built)"; fi
	@if [ -f "$(REGISTRY_UNIVERSE)" ] && [ -f "$(REGISTRY_ATTRIBUTES)" ] && [ -f "$(REGISTRY_NORM)" ]; then $(MAKE) registry-biosamples REGISTRY_OUT=$(PKG_OUT); else echo "no registry sample tier inputs (REGISTRY_ATTRIBUTES / REGISTRY_NORM) — registry_biosamples not built"; fi
	@if [ -f "$(GUT_STUDIES)" ] && [ -f "$(PKG_OUT)/registry_biosamples.parquet" ]; then $(MAKE) gut-build GUT_OUT=$(PKG_OUT); else echo "no gut scope inputs ($(GUT_STUDIES)) — gut_* tables not built"; fi
	@if [ -f "$(REGISTRY_UNIVERSE)" ] && [ -n "$(wildcard $(REGISTRY_EXTRA))" ]; then $(PY) -m catalog.registry.add_registry_tables --package $(PKG_OUT) --release-id $(RELEASE_ID) --package-version $(VERSION) --previous-dir $(PKG_SRC) $(wildcard $(REGISTRY_EXTRA)); else echo "no extra registry tables ($(REGISTRY_EXTRA))"; fi
	@if [ -d "$(GUT_SANDPIPER_DIR)" ]; then cp $(GUT_SANDPIPER_DIR)/gut_sandpiper_sample_summary.parquet $(GUT_SANDPIPER_DIR)/gut_sandpiper_pca_scores.parquet $(GUT_SANDPIPER_DIR)/gut_sandpiper_pca_loadings.parquet $(GUT_SANDPIPER_DIR)/gut_sandpiper_pca_variance.csv $(GUT_SANDPIPER_DIR)/gut_sandpiper_study_coverage.csv $(PKG_OUT)/ && cp $(GUT_SANDPIPER_DIR)/GUT_SANDPIPER_REPORT.md $(PKG_OUT)/ && $(PY) scripts/gut_sandpiper_panels.py --genus $(GUT_SANDPIPER_DIR)/gut_sandpiper_sample_genus.parquet --summary $(GUT_SANDPIPER_DIR)/gut_sandpiper_sample_summary.parquet --wide $(PKG_OUT)/gut_sample_metadata_wide.parquet --out $(PKG_OUT)/gut_sandpiper_study_panels.parquet; else echo "no gut Sandpiper tables ($(GUT_SANDPIPER_DIR))"; fi
	$(MAKE) package-docs
	# VERSION.json must carry the NEW version before the notes are generated (release_notes reads it for the header);
	# the second make_version run re-hashes the package with RELEASE_NOTES included, the third checks (R1-11)
	$(PY) -m catalog.make_version --package $(PKG_OUT) --build-date $(BUILD_DATE) --zip $(PKG_ZIP_OUT)
	$(MAKE) release-notes
	$(PY) -m catalog.make_version --package $(PKG_OUT) --build-date $(BUILD_DATE) --zip $(PKG_ZIP_OUT)
	$(PY) -m catalog.make_version --package $(PKG_OUT) --check --zip $(PKG_ZIP_OUT)
	@ls -la $(PKG_ZIP_OUT) $(RELEASE_NOTES) && cat $(PKG_ZIP_OUT).sha256

apply-verdicts:  ## stage 2→5 — append validated verdicts for NEW studies (VERDICTS=<parquet>) to universe_studies_all + study_verdict_history
	@test -f "$(VERDICTS)" || { echo "VERDICTS=$(VERDICTS) not found"; exit 1; }
	$(PY) -m catalog.triage.apply_verdicts --package $(PKG_OUT) --verdicts $(VERDICTS) --stage $(notdir $(basename $(VERDICTS)))_session_review --date $(BUILD_DATE)

package-merge:   ## assemble a package from parts (v1.2 tables + Sandpiper dir + authors dir) with build_package.py — used for 1.2.x
	$(PY) -m catalog.build_package --v12 $(PKG_SRC) --sandpiper $(SP_DIR)/sp --authors $(BUILD)/authors_$(CYCLE) --out $(PKG_OUT) --build-date $(BUILD_DATE) --package-version $(VERSION) --zip $(PKG_ZIP_OUT)

check-reports:   ## fail when a report the site links to is missing from $(REPORTS) (R1-08; list = config/inputs.json group `reports`)
	$(PY) scripts/check_reports.py $(REPORTS)

plot-coverage:   ## regenerate field_coverage.png from the package's field_coverage_summary.csv (deterministic)
	$(PY) scripts/plot_field_coverage.py --summary $(PKG_OUT)/field_coverage_summary.csv --out $(REPORTS)/field_coverage.png

site:            ## stage 6 — build the static site from the package (deterministic build date from VERSION.json)
	@test -n "$(BASE_URL)" && test "$(BASE_URL)" != "$(PLACEHOLDER_URL)" || { echo "config/site.yaml base_url is the placeholder ($(PLACEHOLDER_URL))"; exit 1; }
	$(MAKE) check-reports
	$(PY) site_generator/gen/build_site.py --package $(PKG_OUT) --out $(SITE_OUT) \
	  --package-zip $(PKG_ZIP_OUT) --reports $(REPORTS) --atlas-data $(ATLAS_DATA) \
	  --base-url $(BASE_URL) --build-date $$($(PY) -c "import json;print(json.load(open('$(PKG_OUT)/VERSION.json'))['build_date'])")
	cp $(PKG_OUT)/VERSION.json $(SITE_OUT)/data/VERSION.json

verify:          ## local subset of .github/workflows/verify.yml (link check + duckdb read + manifest/zip check); Playwright runs in Actions
	$(PY) site_generator/gen/check_links.py $(SITE_OUT)
	$(PY) -c "import duckdb,glob;[print(duckdb.sql(f\"select count(*) from read_parquet('{f}')\").fetchone()[0], f) for f in glob.glob('$(SITE_OUT)/data/**/*.parquet', recursive=True)]"
	$(PY) -m catalog.make_version --package $(PKG_OUT) --check --zip $(PKG_ZIP_OUT)

check-credential: ## stage 7 precondition — resolve the github credential through GIT_ASKPASS and `git ls-remote` both repos (R1-15; run in a Claude cell with credentials=["GitHub"])
	$(PY) scripts/git_askpass.py --check $(SITE_CLONE) $(DATA_CLONE)

install-workflows: ## owner bootstrap (once) — copy verify/deploy-pages + the Issue template into the site clone, release.yml into the data clone (R1-05)
	@test -d $(SITE_CLONE)/.git || { echo "site clone missing at $(SITE_CLONE)"; exit 1; }
	@test -d $(DATA_CLONE)/.git || { echo "data clone missing at $(DATA_CLONE)"; exit 1; }
	mkdir -p $(SITE_CLONE)/.github/workflows $(SITE_CLONE)/.github/ISSUE_TEMPLATE $(DATA_CLONE)/.github/workflows
	cp .github/workflows/verify.yml .github/workflows/deploy-pages.yml $(SITE_CLONE)/.github/workflows/
	cp .github/ISSUE_TEMPLATE/catalog-finding.yml .github/ISSUE_TEMPLATE/catalog-contribution.yml site_generator/gen/issue_templates/simple-finding.yml site_generator/gen/issue_templates/share-metadata.yml site_generator/gen/issue_templates/verify-metadata.yml $(SITE_CLONE)/.github/ISSUE_TEMPLATE/
	cp .github/workflows/release.yml $(DATA_CLONE)/.github/workflows/
	@echo "now commit + push .github/ in both clones (owner; docs/RUNBOOK.md 'Owner bootstrap (once)')"

publish-branch:  ## stage 7 — copy site + package into the clones, commit on release/$(VERSION), tag; NEVER touches main
	@test -f $(SITE_OUT)/index.html && test -f $(PKG_OUT)/VERSION.json || { echo "run make package site verify first"; exit 1; }
	@test -d $(SITE_CLONE)/.git || { echo "site clone missing at $(SITE_CLONE) (docs/DATA_LAYOUT.md)"; exit 1; }
	@test -d $(DATA_CLONE)/.git || { echo "data clone missing at $(DATA_CLONE)"; exit 1; }
	cd $(SITE_CLONE) && git fetch -q origin && git checkout -q -B release/$(VERSION) origin/main
	# rsync exits 23 on this mount because utimensat on the clone root is refused (harmless); tolerate it and PROVE completeness with a checksum dry-run that must list nothing
	rsync -a --delete --exclude .git --exclude '.github/workflows/*' --exclude '.github/ISSUE_TEMPLATE/*' --exclude .DS_Store $(SITE_OUT)/ $(SITE_CLONE)/ || [ $$? -eq 23 ]  # site repo owns its installed workflows/template (make install-workflows)
	@n=$$(rsync -rcn --delete --exclude .git --exclude '.github/workflows/*' --exclude '.github/ISSUE_TEMPLATE/*' --exclude .DS_Store $(SITE_OUT)/ $(SITE_CLONE)/ 2>&1 | grep -v '^rsync(' | grep -vc '^$$' || true); test "$$n" = "0" || { echo "site clone differs from build in $$n paths"; exit 1; }
	cd $(SITE_CLONE) && git add -A && git commit -q -m "site $(VERSION) ($(BUILD_DATE))" && git tag -f site-v$(VERSION)
	cd $(DATA_CLONE) && git fetch -q origin && git checkout -q -B release/$(VERSION) origin/main
	(rsync -a --delete $(PKG_OUT)/ $(DATA_CLONE)/package/ || [ $$? -eq 23 ]) && mkdir -p $(DATA_CLONE)/audit && (rsync -a audit/ $(DATA_CLONE)/audit/ || [ $$? -eq 23 ])
	@n=$$(rsync -rcn --delete $(PKG_OUT)/ $(DATA_CLONE)/package/ 2>&1 | grep -v '^rsync(' | grep -vc '^$$' || true); test "$$n" = "0" || { echo "data clone package/ differs from build in $$n paths"; exit 1; }
	# Large release assets (Sandpiper long tables in < 90 MB parts, registry_runs) are NOT committed on the release branch (owner
	# 2026-09-30: no Sandpiper history in the data repo). They are staged in a throw-away git repo under /tmp and force-pushed as the
	# single-commit orphan branch `release-assets`; release.yml checks that branch out (depth 1) and attaches assets/* to the Release.
	rm -rf $(DATA_CLONE)/assets $(ASSETS_WT) && mkdir -p $(ASSETS_WT)/assets
	@if [ -f "$(GUT_SANDPIPER_DIR)/gut_sandpiper_sample_genus.parquet" ]; then for t in genus species; do $(PY) scripts/split_parquet.py $(GUT_SANDPIPER_DIR)/gut_sandpiper_sample_$$t.parquet $(ASSETS_WT)/assets/gut_sandpiper_sample_$${t}_v$(VERSION) --max-mb 90; done; echo "Sandpiper long tables staged"; fi
	# registry_runs is re-written with zstd (snappy copy passed 100 MB at R2026.13: 128 MB → 75 MB) so it stays one file below GitHub's hard limit
	@if [ -f "$(REGISTRY_RUNS)" ]; then $(PY) -c "import pyarrow.parquet as pq,sys; pq.write_table(pq.read_table(sys.argv[1]), sys.argv[2], compression='zstd', compression_level=9, row_group_size=200000)" $(REGISTRY_RUNS) $(ASSETS_WT)/assets/registry_runs_v$(VERSION).parquet && (cd $(ASSETS_WT)/assets && shasum -a 256 registry_runs_v$(VERSION).parquet > registry_runs_v$(VERSION).parquet.sha256); echo "registry_runs asset staged"; fi
	echo "$(VERSION)" > $(ASSETS_WT)/assets/ASSETS_VERSION.txt
	# the sandbox refuses to create a `.git` directory, so the git dir lives beside the work tree (GIT_DIR); the push command below must set the same two variables
	rm -rf $(ASSETS_WT).gitdir && cd $(ASSETS_WT) && export GIT_DIR=$(ASSETS_WT).gitdir GIT_WORK_TREE=$(ASSETS_WT) && git init -q && git add -A && git -c user.name=release-bot -c user.email=release-bot@localhost commit -qm "release assets $(VERSION) ($(BUILD_DATE)) — orphan branch, no history" && echo "assets repo ready at $(ASSETS_WT) (git dir $(ASSETS_WT).gitdir)"
	cd $(DATA_CLONE) && git add -A && git commit -q -m "data package $(VERSION) ($(BUILD_DATE))" && git tag -f data-v$(VERSION)
	@echo "push with the credential helper (docs/SECURITY.md):"
	@echo "  git -C $(SITE_CLONE) push origin release/$(VERSION) site-v$(VERSION)"
	@echo "  GIT_DIR=$(ASSETS_WT).gitdir GIT_WORK_TREE=$(ASSETS_WT) git push --force $$(git -C $(DATA_CLONE) remote get-url origin) HEAD:refs/heads/release-assets   # BEFORE the data tag"
	@echo "  git -C $(DATA_CLONE) push origin release/$(VERSION) data-v$(VERSION)"

# ---------------------------------------------------------------- curated scope gut_all (config/packs/gut.yaml; R2026.7)
GUT_DIR      ?= $(DATA)/gut
GUT_STUDIES  ?= $(GUT_DIR)/gut_studies.parquet
GUT_R1       ?= $(GUT_DIR)/gut_r1_determinations.parquet
GUT_R1_EXTRA ?= $(GUT_DIR)/gut_condition_abx_determinations.parquet
GUT_R2_GLOB  ?= $(GUT_DIR)/r2/gut_r2_determinations_shard_*.parquet
# r3/ (R2026.8 cohort statements) + r3b/ (R2026.12 lifestyle / location / collection_date); r4/ (R2026.7) + r4b/shards (R2026.12). No trailing comments: Make keeps the blanks.
GUT_R3_GLOB  ?= $(GUT_DIR)/r3*/gut_r3*_determinations_merged.parquet
GUT_R4_GLOB  ?= $(GUT_DIR)/r4*/gut_r4*_determinations_shard_*.parquet
GUT_COND_MAP ?= $(GUT_DIR)/gut_health_condition_map.parquet
GUT_ABX_MAP  ?= $(GUT_DIR)/gut_antibiotic_map.parquet
# 1.12.0 (R2026.12): route R1 for the new pack fields (collection_date, location_*, latitude/longitude, lifestyle) — output of gut-newfields-r1
GUT_R1_NEWFIELDS ?= $(GUT_DIR)/gut_r1_newfields_determinations.parquet
# data-quality corrections (retire / recode) from the adjudication leaf — optional
GUT_CORRECTIONS ?= $(GUT_DIR)/dq_corrections.parquet
# harvested BioSample attribute rows of the catalog studies (artifact; bootstrap materialises it) — input of gut-newfields-r1
GUT_ATTRIBUTES   ?= $(GUT_DIR)/gut_biosample_attributes.parquet
# 1.13.0 (R2026.13): route R1 for the new fields v2 (diet, smoking_status, medication, stool_consistency_bristol) — output of gut-newfields-r1-v2
GUT_R1_NEWFIELDS_V2 ?= $(GUT_DIR)/gut_r1_newfields_v2_determinations.parquet
# interventions (R2026.15): per-sample arms (R1) and the study-level classification shards (R4, abstracts)
GUT_R1_INTERVENTIONS ?= $(GUT_DIR)/interventions/gut_r1_intervention_determinations.parquet
GUT_R1_INFANT ?= $(GUT_DIR)/r1_infant/gut_r1_infant_determinations.parquet
GUT_SAMPLE_EXCLUSIONS ?= config/sample_exclusions.csv
GUT_DEEP_GLOB ?= $(GUT_DIR)/deep/deep_determinations_shard_*.parquet
GUT_IV_STUDY_GLOB ?= $(GUT_DIR)/interventions/gut_intervention_studies_shard_*.parquet
# NCBI SRA bases for runs ENA reports with base_count 0 (dbGaP / not mirrored): scripts/fill_run_bases.py (R2026.16)
RUN_BASES_NCBI ?= $(DATA)/registry/run_bases_ncbi.parquet
# attribute rows whose keys match diet / smoking / medication / stool / alcohol / activity patterns (artifact gut_biosample_attributes_newfields_v2) — input of gut-newfields-r1-v2
GUT_ATTRIBUTES_V2   ?= $(GUT_DIR)/gut_biosample_attributes_newfields_v2.parquet
GUT_OUT      ?= $(BUILD)/gut
# whole-catalog Sandpiper tables (leaf outputs; filter_gut.py + build_gut_tables.py regenerate them from the bulk snapshot)
GUT_SANDPIPER_DIR ?= $(GUT_DIR)/sandpiper
# precomputed Atlas payload (taxa.json, matrix_*.bin, observations.json, obs/) — pages/atlas.py precompute + scripts/atlas_observations.py
ATLAS_DATA   ?= $(GUT_DIR)/atlas

atlas-observations: ## recompute the Atlas observation cards (obs/*.png + obs/*.csv + observations.json) from the Sandpiper tables + the released wide table → $(ATLAS_DATA); HDI = site_generator/gen/data/undp_hdr2025_hdi_2023.csv
	@test -f "$(GUT_SANDPIPER_DIR)/gut_sandpiper_sample_genus.parquet" || { echo "Sandpiper genus table missing: $(GUT_SANDPIPER_DIR)"; exit 1; }
	$(PY) scripts/atlas_observations.py --genus $(GUT_SANDPIPER_DIR)/gut_sandpiper_sample_genus.parquet --species $(GUT_SANDPIPER_DIR)/gut_sandpiper_sample_species.parquet \
	  --summary $(GUT_SANDPIPER_DIR)/gut_sandpiper_sample_summary.parquet --pca $(GUT_SANDPIPER_DIR)/gut_sandpiper_pca_scores.parquet \
	  --wide $(PKG_SRC)/gut_sample_metadata_wide.parquet --out $(ATLAS_DATA) --generated-from "package $(VERSION) wide table + Sandpiper genus/species tables"

gut-build:       ## curated scope gut_all — gut_studies / gut_sample_metadata_wide / gut_sample_determinations / gut_runs from registry_biosamples + registry_runs + R1/R2/R3/R4 leaf outputs + the infant tables
	mkdir -p $(GUT_OUT) $(BUILD)/gut
	$(PY) -m catalog.scopes.build_gut_scope --studies $(GUT_STUDIES) --registry-studies $(PKG_OUT)/registry_studies.parquet --biosamples $(PKG_OUT)/registry_biosamples.parquet \
	  --package $(PKG_OUT) --r1 $(GUT_R1) --r1-extra "$(GUT_R1_EXTRA)" --r1-newfields "$(GUT_R1_NEWFIELDS)" --r1-newfields-v2 "$(GUT_R1_NEWFIELDS_V2)" --r1-interventions "$(GUT_R1_INTERVENTIONS)" --r1-infant "$(GUT_R1_INFANT)" --sample-exclusions "$(GUT_SAMPLE_EXCLUSIONS)" --deep-glob "$(GUT_DEEP_GLOB)" --interventions-study "$(GUT_IV_STUDY_GLOB)" --run-bases "$(RUN_BASES_NCBI)" --corrections "$(GUT_CORRECTIONS)" --r2-glob "$(GUT_R2_GLOB)" --r3-glob "$(GUT_R3_GLOB)" --r4-glob "$(GUT_R4_GLOB)" --condition-map $(GUT_COND_MAP) --antibiotic-map $(GUT_ABX_MAP) \
	  --registry-runs $(REGISTRY_RUNS) --registry-sandpiper $(REGISTRY_SANDPIPER) \
	  --out $(GUT_OUT) --summary $(BUILD)/gut/gut_scope_summary.json --release-id $(RELEASE_ID) --package-version $(VERSION) --previous-dir $(PKG_SRC)

gut-newfields-r1: ## stage 8 leaf (Claude session for the utility-model steps; ≈ 0.3 M tokens) — R1 rows for collection_date / location_* / latitude+longitude / lifestyle from the BioSample attributes → $(GUT_R1_NEWFIELDS) + gut_location_map / gut_lifestyle_map / rejects / conflicts
	@test -f "$(GUT_ATTRIBUTES)" || { echo "attribute rows missing: $(GUT_ATTRIBUTES) (artifact gut_biosample_attributes; bootstrap.py)"; exit 1; }
	$(PY) -m catalog.scopes.newfields_r1 --attributes $(GUT_ATTRIBUTES) --wide $(PKG_SRC)/gut_sample_metadata_wide.parquet --gut-studies $(GUT_STUDIES) \
	  --registry-runs $(REGISTRY_RUNS) --registry-sandpiper $(REGISTRY_SANDPIPER) --out-dir $(GUT_DIR) --release-id $(RELEASE_ID) --package-version $(VERSION) \
	  $(if $(GUT_LOCATION_MAP),--location-map $(GUT_LOCATION_MAP),) $(if $(GUT_LIFESTYLE_MAP),--lifestyle-map $(GUT_LIFESTYLE_MAP),) $(if $(NO_LLM),--no-llm,) $(if $(REVERSE_GEOCODE),--reverse-geocode,)
	@rm -f $(GUT_OUT)/gut_sample_determinations_conflicts.parquet 2>/dev/null; true

gut-newfields-r1-v2: ## stage 8 leaf (Claude session for the utility-model steps; ≈ 0.1 M tokens) — R1 rows for diet / smoking_status / medication / stool_consistency_bristol from the BioSample attributes → $(GUT_R1_NEWFIELDS_V2) + gut_diet_map / gut_smoking_map / gut_medication_map / rejects / conflicts
	@test -f "$(GUT_ATTRIBUTES_V2)" || { echo "attribute rows missing: $(GUT_ATTRIBUTES_V2) (artifact gut_biosample_attributes_newfields_v2; bootstrap.py)"; exit 1; }
	$(PY) -m catalog.scopes.newfields_r1_v2 --attributes $(GUT_ATTRIBUTES_V2) --wide $(PKG_SRC)/gut_sample_metadata_wide.parquet --gut-studies $(GUT_STUDIES) \
	  --gut-runs $(PKG_SRC)/gut_runs.parquet --registry-runs $(REGISTRY_RUNS) --registry-sandpiper $(REGISTRY_SANDPIPER) --out-dir $(GUT_DIR) --release-id $(RELEASE_ID) --package-version $(VERSION) \
	  $(if $(GUT_DIET_MAP),--diet-map $(GUT_DIET_MAP),) $(if $(GUT_MEDICATION_MAP),--medication-map $(GUT_MEDICATION_MAP),) $(if $(NO_LLM),--no-llm,)

# REGISTRY_UNIVERSE: enumeration track output (frozen columns: audit/registry_schema.json)
REGISTRY_UNIVERSE ?= $(DATA)/registry/registry_universe_studies.parquet
REGISTRY_AUDIT    ?= $(DATA)/registry/registry_universe_audit.csv
REGISTRY_LLM      ?=
REGISTRY_OUT      ?= $(BUILD)/registry
REGISTRY_FIXTURE  := tests/data/registry_fixture_universe.parquet
# REGISTRY_RUNS: ≈70 MB run-level table: shipped as a Release ASSET (data clone assets/), never inside package/ or the site
REGISTRY_RUNS     ?= $(DATA)/registry/registry_runs.parquet
# REGISTRY_SANDPIPER: run-level Sandpiper join (run_accession, study_accession, sandpiper_profiled) → n_runs_sandpiper
REGISTRY_SANDPIPER ?= $(DATA)/registry/registry_runs_sandpiper.parquet
# S2 sample tier: harvested BioSample attributes (working_data artifact) + the normalised (field,key,value) map; side tables shipped as-is
REGISTRY_ATTRIBUTES ?= $(DATA)/registry/registry_biosample_attributes.parquet
REGISTRY_NORM       ?= $(DATA)/registry/registry_pairs_normalised.parquet
REGISTRY_EXTRA      ?= $(DATA)/registry/registry_study_papers.parquet $(DATA)/registry/registry_authors.parquet $(DATA)/registry/registry_bioproject_records.parquet

registry-fixture: ## registry — rebuild the 200-study test fixture from the 1.5.0 universe (V3_STUDIES=… FRAME_FREE=… parquet paths)
	$(PY) -m catalog.registry.build_registry --make-fixture --v3-studies $(V3_STUDIES) --frame-free $(FRAME_FREE) --infant $(PKG_SRC)/universe_studies_all.parquet --out $(REGISTRY_FIXTURE)

registry-classify-det: ## registry — deterministic classification of the registry universe → $(REGISTRY_OUT)/registry_classification_det.parquet
	mkdir -p $(REGISTRY_OUT)
	$(PY) -c "import pandas as pd, sys; from catalog.registry.build_registry import normalise_universe; from catalog.registry.classify_deterministic import classify_frame; \
	  u=pd.read_parquet('$(REGISTRY_UNIVERSE)' if __import__('os').path.exists('$(REGISTRY_UNIVERSE)') else '$(REGISTRY_FIXTURE)'); \
	  inf=pd.read_parquet('$(PKG_SRC)/universe_studies_all.parquet'); inf=inf[inf.release_retired.isna()] if 'release_retired' in inf else inf; \
	  d=classify_frame(normalise_universe(u), inf[['study_accession','triage_verdict','reason_code','body_site_call']]); \
	  d.to_parquet('$(REGISTRY_OUT)/registry_classification_det.parquet', index=False); print(len(d), 'studies;', int(d.needs_llm.sum()), 'need LLM')"

registry-biosamples: ## registry S2 — registry_biosamples.parquet + study roll-up columns (needs REGISTRY_ATTRIBUTES + REGISTRY_NORM; studies from REGISTRY_OUT)
	$(PY) -m catalog.registry.build_biosamples --attributes $(REGISTRY_ATTRIBUTES) --norm $(REGISTRY_NORM) --studies $(REGISTRY_OUT)/registry_studies.parquet \
	  --out $(REGISTRY_OUT) --summary $(BUILD)/registry/registry_biosamples_summary.json --release-id $(RELEASE_ID) --package-version $(VERSION) $$( [ -f $(PKG_SRC)/registry_biosamples.parquet ] && echo --previous $(PKG_SRC)/registry_biosamples.parquet )

registry-build:  ## registry — registry_studies.parquet + REGISTRY_REPORT.md (uses the fixture when REGISTRY_UNIVERSE is absent; REGISTRY_LLM optional)
	mkdir -p $(REGISTRY_OUT)
	$(PY) -m catalog.registry.build_registry --universe $$( [ -f $(REGISTRY_UNIVERSE) ] && echo $(REGISTRY_UNIVERSE) || echo $(REGISTRY_FIXTURE) ) \
	  $$( [ -f $(REGISTRY_UNIVERSE) ] || echo --fixture ) --infant $(PKG_SRC)/universe_studies_all.parquet \
	  $$( [ -n "$(REGISTRY_LLM)" ] && echo --llm $(REGISTRY_LLM) ) $$( [ -f $(REGISTRY_AUDIT) ] && echo --audit $(REGISTRY_AUDIT) ) $$( [ -f $(REGISTRY_SANDPIPER) ] && echo --sandpiper-runs $(REGISTRY_SANDPIPER) ) \
	  --out $(REGISTRY_OUT) --release-id $(RELEASE_ID) --package-version $(VERSION) $$( [ -f $(PKG_SRC)/registry_studies.parquet ] && echo --previous $(PKG_SRC)/registry_studies.parquet )

clean:           ## remove build/
	rm -rf $(BUILD)
